### ISSUE TITLE
Client-Side error when using EditableText.useMethods = false

### ISSUE THREAD

**Issue by workflow** [JackAdams/meteor-editable-text#10]
Whenever I try setting `EditableText.useMethods` to `false`, I get the following error on any attempted field update:

```
 Uncaught TypeError: Cannot read property '0' of undefined   editable_text.js:97 
 EditableText.update    editable_text.js:241
 EditableText._makeUpdate   editable_text.js:356
 EditableText.okCancelEvents.ok editable_text.js:174
 EditableText._okCancelEvents.events.(anonymous function)   template.js:278
 (anonymous function)   view.js:760
 (anonymous function)   view.js:414
 Blaze._withCurrentView view.js:759
 (anonymous function)   events.js:47
 (anonymous function)   jquery.js:4665
 jQuery.event.dispatch  jquery.js:4333
 jQuery.event.add.elemData.handle
```

Can you reproduce?

Happy to help debugging with all I can here.

**Comment by JackAdams** [comment]
Thanks for the report. I'll look into it.  If you could give the widget code that does this, that would help - e.g. `{{> editableText collection="posts" field="body"}}`.  A minimal repro on meteorpad.com would be really helpful, if you have time. :-)

[EDIT] Never mind -- I was able to reproduce.  I'll release a patched version of the package later today.
