### ISSUE TITLE
port to semantic-ui

### ISSUE THREAD

**Issue by miguelalarcos** [JackAdams/meteor-editable-text#12]
Hi, first of all thanks for this project. I like it a lot.

I would like to say that I am trying to port the project to semantic-ui. I have rewritten the html file (if you want I can post it here so you can see it) and add some code:

``` coffee
Template.wysiwyg.rendered = ->
  $('.ui.dropdown').dropdown()

Template.wysiwyg.events
  'mousedown .ui.dropdown': (e,t)->
    e.preventDefault()
```

I was wondering if I should take care of something especial or if it's essentially modify the html (I still have some problems I hope to resolve soon).

**Comment by JackAdams** [comment]
Hi Miguel,

Great to hear you're porting this to semantic-ui.

I think the only thing to remember is that if you want a save button, you'll need to make sure the button element has `wysiwyg-save-button` as one of its classes. Other than that, I think it's just a matter of changing the files in the `babrahams:editable-text-wysiwyg-bootstrap-3` package until the editor looks and behaves like you want it to.

Behind the scenes, it will still be using a modified version of bootstrap-wysiwyg to make the content-editable area behave like a rich text editor, but this is just javascript (with jquery) and doesn't actually have anything to do with bootstrap.

If you need help with anything, let me know.  I'm happy to help with debugging once you've got a repo (or atmosphere package) up.
