### ISSUE TITLE
afterUpdate not working

### ISSUE THREAD

**Issue by milanzigmond** [JackAdams/meteor-editable-text#13]
{{> editableText collection="posts" field="body" afterUpdate="logIt"}} 
is working in version 0.7.7 but NOT working in version 0.7.11 

packages list
working: http://prntscr.com/69zbjo
NOT working (after meteor update): http://prntscr.com/69zboq

the code remains the same, just updated the package, 
I used your example editable-text-demo for this test, latest meteor

**Comment by JackAdams** [comment]
Thanks for this @milanzigmond.  I'll look into it.

**Comment by JackAdams** [comment]
Version 0.7.12 fixes this issue.  Thanks so much for reporting it.
