### ISSUE TITLE
Doesn't work align center and right in wysiwyg mode

### ISSUE THREAD

**Issue by galkinsergeyv** [JackAdams/meteor-editable-text#14]
When i try align center and then focus out text remains unchanged.
You can see it in this example http://editable-text.meteor.com/

**Comment by JackAdams** [comment]
Yep. You're right. That's a nasty little cross-browser bug. For instance, it works in FF, but not in Chrome.

**Comment by JackAdams** [comment]
Fixed in latest release (0.7.14).
