### ISSUE TITLE
cannot edit if field content is blank

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#15]
if the field I want is in a cell in a table, I would like to be able to click to edit the cell, even if the cell content is empty

**Comment by JackAdams** [comment]
Hi -- sorry for the late response. This is an undocumented feature but if you put the class `editable-text-trigger` on the `td` element then any click on the cell will trigger the editing.

**Comment by dpatte** [comment]
Thaks. Works great!
