### ISSUE TITLE
Edit cancels when clicking AltGr

### ISSUE THREAD

**Issue by albertovilla** [JackAdams/meteor-editable-text#17]
Hi, when I'm editing a field and click AltGr to introduce a special character (e.g. # or @ in Spanish keyboard) the edit cancels and I cannot introduce the character. I think it has to do with the okCancelEvents but I don't know how to solve it.

Any suggestion on how could I overcome this problem?

**Comment by JackAdams** [comment]
Thanks for reporting this. I'll look into it in a few hours time. As a temporary workaround, you could set `saveOnFocusout=false` when initializing the widget. Let me know if that **doesn't** help.

**Comment by albertovilla** [comment]
Thanks a lot, that solved the problem, from my side this issue can be closed, now it works perfectly.

**Comment by JackAdams** [comment]
Cool. Thanks for letting me know it worked. I'll still take a look and see what the problem is, if I can.
