### ISSUE TITLE
The document passed in afterUpdate / afterInsert is not up to date

### ISSUE THREAD

**Issue by albertovilla** [JackAdams/meteor-editable-text#18]
Hi,

I have a workaround already for this but I think the afterUpdate / afterInsert callback doesn't work as expected. I've assigned a callback for both afterUpdate and afterInsert as follows:

```
afterUpdate="generateLabels"
```

In the callback the document received is the one prior editing and not the one after the edit i.e. the one which has been introduced in the database. I have checked using the code below

```
EditableText.registerCallbacks({
    generateLabels: function(ideaDoc) {
        console.log (ideaDoc.title);
        console.log (Ideas.findOne({_id: ideaDoc._id}).title);
    }
});
```

**Comment by JackAdams** [comment]
I'll check into it. Thanks for reporting this.
