### ISSUE TITLE
adding an URL on IE

### ISSUE THREAD

**Issue by darkship** [JackAdams/meteor-editable-text#19]
Hello,

I tested your example http://editable-text.meteor.com/ on IE11 with IE9, IE10 and Edge compatibility modes and I couldn't give an URL in

```
<input class="span2" type="text" data-edit="createLink" placeholder="URL">
```

**Comment by JackAdams** [comment]
Thanks for reporting this. What exactly happened? Did the URL get stripped out when the content got saved or did it just not apply the link to the selected text in the first place?

**Comment by darkship** [comment]
After selecting my text in the editable post, I opened the wysiwyg, clicked on the "create url" button then the dropdown showed the input and add button but I couldn't write into the input to give an URL.

**Comment by JackAdams** [comment]
Okay, got it.  I'll see if I can figure out what's going on. Thanks again for reporting this.

**Comment by darkship** [comment]
Any news ?

**Comment by JackAdams** [comment]
No.  It looks like it's the code I pinched from an editor a couple of years back that doesn't work on IE.  (I don't have IE on my laptop to test on.)  I don't think this is going to get fixed, short of someone submitting a PR.  Sorry!
