### ISSUE TITLE
Working with arrays and subdocuments

### ISSUE THREAD

**Issue by workflow** [JackAdams/meteor-editable-text#21]
First and foremost, thank you for this great package!

Is there currently any way to make the editable-text widget work with an array of subdocuments?

Specifically, I have an array of comments that are stored on an object like so:

```
"comments" : [ 
        {
            "createdAt" : ISODate("2015-03-27T14:24:47.087Z"),
            "createdBy" : "PKgGc6kfJeik2BASM",
            "privacy" : "Public",
            "text" : "heyho buddies!",
            "id" : "Wd2YTRF6Mpoz9RaAa"
        }, 
        {
            "createdAt" : ISODate("2015-03-27T14:24:57.419Z"),
            "createdBy" : "CYTYJXMWCZ8PavMxk",
            "privacy" : "Public",
            "text" : "Yoho Test!",
            "id" : "XffaMTGPwP4YQRp5o"
        }
    ],
```

...and I would like to add `{{> editableText}}` widgets for the `text` of every comment on the parent collection.

**Comment by JackAdams** [comment]
Thanks for the kind words.  This is possible, it just takes a little more work.

In the template:

```
{{#each comments}} 
  {{> editableText context=.. collection="posts" field=field}}
{{/each}}
```

In the helpers for the template:

```
field : function() {
  var field = 'comment.' + this.index + '.text';
  return field; 
},
comments : function () {
  return _.map(this.comments, function (comment, index) {
    return _.extend(comment, {index: index});
  }
}
```

**Comment by ajschmaltz** [comment]
I've followed the steps exactly here but can't quite get it working.  Is the context=.. important in this case?  I've left it out...

**Comment by JackAdams** [comment]
Yes, that's so it targets the correct db document for update.  Otherwise, the context is one of the subdocuments from the array.

I've just updated the example to include dynamic indexing of the comments.  I think `@index` or something like that is going to be available in Meteor 1.2, which might help with this sort of thing.

**Comment by ajschmaltz** [comment]
Wow, thank you.

**Comment by ajschmaltz** [comment]
This works flawlessly but I am having a hard time understanding what to change if post = Post.findOne(...
