### ISSUE TITLE
issue with beforeUpdate?

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#22]
I have the following in a template

{{> editableText collection="contacts" field="firstName" acceptEmpty=true beforeUpdate="addUpdateDate"}}

And in my lib folder where I define the contacts collection i have

EditableText.registerCallbacks(
{
  addUpdateDate: function(doc) { return _.extend(doc,{updated: new Date()}); }
});

When I click to edit the editable field it works, and the doc is updated with the new contact firstName, but the 'updated' field is not updated. I can't determine why the updated field is not saved when the doc is updated.

I looked at doc within the addUpdateDate function and the function is triggered, and updated is indeed being set in doc to the current time. But after the update, the new time is not in the doc - it does not get modified by the update.

I should point out I am also using Collection2; and updated, as well as a few other fields are required fields, but they do show up if I look at doc in above the callback.

Also, not really related, but in the callback, is it really required that I return doc, as I am doing, since extend updates the doc object in-place anyway.

**Comment by JackAdams** [comment]
Thanks for reporting this. I'll look into it and get back to you.

**Comment by JackAdams** [comment]
Doh!  Forgetting how my own package works ...

The only field that this widget updates is the `field` specified in the parameters, in your case `firstName`.  To update other fields, you'll have to write something like this in the callback:

```
Contacts.update({_id: doc._id}, {updated: new Date()});
```

**Comment by dpatte** [comment]
Thanks.

That's unfortunate. Your documentation actually suggests otherwise (see your documentation regarding registering callbacks - the actual sample function for the documentation and the comment... 'Notice that returning a modified document in a beforeInsert function will mean that this is the version of the document that will be inserted into the db. ')

**Comment by JackAdams** [comment]
Yeah, that's for inserts only, not for updates.  I'll amend the documentation to make that distinction explicit.
