### ISSUE TITLE
option userCanEdit has no effect

### ISSUE THREAD

**Issue by derdaumen** [JackAdams/meteor-editable-text#24]
I tried to use the userCanEdit option with a helper function that checks if the current User has a role with the necessary rights. After that didn't work I tested the option like this:

``` HTML
{{> editableText userCanEdit=false collection="myCollection" field="textField" doc=currentDocument wysiwyg=true}}
```

and I was still able to edit the text. Am I not seeing or understanding something?
I would be grateful for help.

Thank you for this great package. Helped me a lot!

**Comment by JackAdams** [comment]
Sorry about the late reply -- you're absolutely right.  I had the logic wrong in the template helper.  Fixed in the latest release.
