### ISSUE TITLE
Options to configure htmlSantizer 

### ISSUE THREAD

**Issue by chongwang87** [JackAdams/meteor-editable-text#26]
Is there a way to set global setting to configure htmlSantizer option like allowTags & allowAttributes.

**Comment by JackAdams** [comment]
Yep.  Overwrite `EditableText.allowedHTML` with whatever you like.  This is the default:

```
EditableText.allowedHtml = {
  allowedTags: sanitizeHtml.defaults.allowedTags.concat(['sub','sup','font','i']),
  allowedAttributes: _.extend(sanitizeHtml.defaults.allowedAttributes,{font:['size','face'],div:['align','style'],td:['rowspan','colspan','style'],a:['href','target','class'],i:['class']}),
  allowedSchemes:['http','https','ftp','mailto']
};
```

**Comment by chongwang87** [comment]
this should put under server or client?
can i just override the default by not using concat and extend?

**Comment by JackAdams** [comment]
Yes, you can override the defaults by not using concat and extend -- use an array and an object respectively.  This should go in a file that is common to client and server.

**Comment by chongwang87** [comment]
I create a file call EditableText.js under `client/lib/config` with the example code you provided.
But there is error from the console `Uncaught ReferenceError: sanitizeHtml is not defined`
The `{{>editableText}}` code is located at `client/views`

**Comment by JackAdams** [comment]
You're right.  This is a serious issue.  I'll be releasing a new version within the next 24 hours.  Thank you for bringing this to my attention.

**Comment by JackAdams** [comment]
Okay. That should be fixed in the latest release.
