### ISSUE TITLE
Assign multiple userCanEdit function

### ISSUE THREAD

**Issue by chongwang87** [JackAdams/meteor-editable-text#27]
is there a way to define multiple userCanEdit function like "myCompany" for Company collection, and "myAccount" for Account collection.

Examples:

```
{{> editableText userCanEdit=myCompany collection="Company" field="textField" wysiwyg=true}}

{{> editableText userCanEdit=myAccount collection="Account" field="textField" wysiwyg=true}}
```

**Comment by JackAdams** [comment]
As long as `myCompany` and `myAccount` are helpers for the template that the widget appears in, you can define different functions for them.  But this is just client-side for UI stuff.  The real check is done server-side in `EditableText.userCanEdit`. Here, you'd have to do something like:

```
EditableText.userCanEdit = function(doc,Collection) {
  switch (this.collection) {
    case 'company' :
      return _.contains(doc.employees, Meteor.userId());
    break;
    case 'account' :
      return doc.user_id = Meteor.userId();
    break;
    default :
      return false;
  }
}
```
