### ISSUE TITLE
unexpected text escaping

### ISSUE THREAD

**Issue by lexowgroup** [JackAdams/meteor-editable-text#28]
Hello,
When using meteor-editable-text and entering text data into a {{editable-text ...}} template field that includes text that is "escapeable" (e.g. ampersand, etc.), the characters are getting .escape()'d and displayed .unescape()'d. For example, "chicken & rice" is displaying during edit mode as a "chicken & rice", and in non-edit mode as "chicken &amp; rice". Shouldn't the character display normally in both modes?
Thanks for your input!
Stan

**Comment by JackAdams** [comment]
Yes, you're quite right. This is a serious regression. I'll be releasing a fix as soon as possible. Thanks for reporting it.

**Comment by JackAdams** [comment]
Okay. Should be fixed in the latest release.
