### ISSUE TITLE
Exception in template helper: TypeError: Cannot use 'in' operator to search for 'body' in undefined

### ISSUE THREAD

**Issue by tlau** [JackAdams/meteor-editable-text#30]
I get this error when using the editable text widget in either textarea or wysiwyg mode. It seems to be generated by the EditableText.drillDown method, which receives an undefined value for the data context. I'm passing the document in to the template as its context parameter.

Despite the error the widget seems to work properly though. Am I doing something wrong?

Here's a MeteorPad with the error: http://meteorpad.com/pad/GKiMvvKWCTMnni6Qg/EditableTest

**Comment by etaiklein** [comment]
The data context for initializing a new object needs to also be an object.

For example (excuse my coffee):

```
Template.newPost.helpers    
  newPosts: ->  #initialize a new post with 'context=newPosts'
      {
        authorId: Meteor.userId()
        lastEditor: Meteor.userId()
        lastEdited: timestamp()
      }
```

It doesn't exactly answer your question but I hope you'll it helpful.

**Comment by JackAdams** [comment]
Thanks @etaiklein.  I've made a slightly modified version of the meteorpad above, with the issues fixed: http://meteorpad.com/pad/mRkhmMgnCaRfRKKZS/Copy%20of%20Editable%20Test%202
Just leaving this issue open for the moment to remind myself to add some more developer-friendly error messages to this widget's codebase.
