### ISSUE TITLE
Shouldn't Substitute text be hidden when the user cannot edit the field?

### ISSUE THREAD

**Issue by ryanswrt** [JackAdams/meteor-editable-text#31]
Maybe there should be a seperate "emptyText" field to display something when the user cannot edit, and the field is blank; because having a "new post" pencil icon when users cannot actually add a new post or text is a bit confusing.

I would submit a pull request for this, but the widget is a bit gnarly and I could just wrap it in my client code if it's not a feature you'd like to include

**Comment by JackAdams** [comment]
Yeah. Sorry about the brutal html/spacebars template. Any whitespace stuffs up the rendering.

You're absolutely right about the pencil icon being confusing when users can't actually edit a post.  I like your suggestion about the `emptyText` parameter for non-editable, blank fields.  I think I'm going to run with that, provided it's an easy addition to the codebase.

**Comment by JackAdams** [comment]
Okay. Just released a new version that accepts an `emptyText` parameter (not sure about the naming of that) for html to show when a user can't edit; and now it doesn't show the html from the `substitute` parameter when a user can't edit.

**Comment by ryanswrt** [comment]
Great, thanks for the quick resolution! Maybe subsititute might be renamed
to editSubstitute or something like that; although you don't want to break
your API.. readonlySubstitute might be a better name for emptyText too;
Sorry for not thinking of better naming beforehand!
