### ISSUE TITLE
New post & comment button no longer work when using userCanEdit

### ISSUE THREAD

**Issue by LeePower** [JackAdams/meteor-editable-text#32]
Hi, I'm trying to prevent from editing without owner's permission.
I have added this function, and works alright.

```
EditableText.userCanEdit = function(doc,Collection) {
  return this.context.user_id === Meteor.userId(); // same as: doc.user_id === Meteor.userId();
}
```

But whenever I click the new post or new comment button, it doesn't do anything, is there anything I missed? Thank for helping!

**Comment by JackAdams** [comment]
I'll look into it and get back to you as soon as possible.

**Comment by JackAdams** [comment]
You're using the `editable-text-demo` app, right?
You'll need to write:

```
{{#with post_id=_id user_id=currentUser._id}}
      <span class="btn btn-default editable-text-trigger">
          <i class="fa fa-plus"></i>{{> editableText collection="comments" field="text" autoInsert=true beforeInsert="addTimestampToDoc"}}
      </span>
 {{/with}}
```

and

```
newCommentDoc: function() {
   return {user_id: Meteor.userId()}; 
},
```

To make the new documents comply with the `EditableText.userCanEdit` function.

This makes the current user the owner of the documents being inserted.

Note: `currentUser._id` might break if the user is logged out and `currentUser` is undefined.  In that case, you'll probably want to create a helper to write some logic that sorts that out.

**Comment by LeePower** [comment]
Solved! Thank you Jack!
