### ISSUE TITLE
numeric?

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#34]
Thanks for all your help on this.

As mentioned elsewhere, my data is a numeric field. When not editing I call a helper that adds thousands separators, commas, to the number. When editing I display it as the original numeric value without commas. It is the edited numeric value (also numeric) that gets stored back into the db. This work great using the following.

{{> editableText collection="deals" field="cap" value=capH editingValue=cap acceptEmpty=true}}

But even with the latest changes I notice a small issue. If I click on a value such as 99 then click out without editing, it correctly recognizes that the data has not been changed. But if I click on a value such as 1000 (displayed before editing as 1,000  and during editing as 1000) then click out without editing, it thinks it has been changed.

I suspect something in the logic is noticing that the display value is non-numeric which is triggering a change, even though the editingValue and what is sotred in the db is actually numeric. Perhaps the logic should be looking at editingValue not value to determine the type of the db value?

**Comment by JackAdams** [comment]
Yes, you're exactly right. It's checking the wrong value. I'll roll out a fix sometime this weekend.

I really need to write some tests for this package ...

**Comment by JackAdams** [comment]
I made a change that might fix this in the latest release.  Not fully tested, but I'd be interested to hear if things have improved.

**Comment by dpatte** [comment]
I am now using 0.7.25. Actually this now seems worse not better, unfortunately.
Previously, clicking in then out, without editing, only marked formatted items (ie: 1000 is shown as 1,000 when not editing) as updated. Now it marks all items (ie: 999 is shown as 999 when editing or not) as updated.

**Comment by dpatte** [comment]
To clarify. An editable text field is stored in the db as numeric. When not editing, i format it by adding commas (1000 is shown as 1,000). But when I click to edit it is shown as its true numeric value (1000). This works fine, except:
Previously if I clicked on this field then clicked out, then values under 1000 didn't get marked as updated, and values >= 1000 got marked as updated. Since I just clicked in and out, no cases should have been marked as updated.
But now all cases get marked as updated.

**Comment by JackAdams** [comment]
Okay.  I'll take another look at it.  Thanks for the clear explanation of the issue.

**Comment by JackAdams** [comment]
Using 0.7.25, and the following code, everything seems to work as expected:

```
  {{> editableText collection="posts" field="num" type="number" editingValue=dbval value=dbvalwithcommas}}
```

And in the `Template.mytemplate.helpers`:

```
  dbval: function() {
    return this.num;    
  },
  dbvalwithcommas: function() {
    return this.num + ',';  
  }
```

I would put a working repro on meteorpad, but I see that it's cached an old version of the package (0.7.19).

**Comment by dpatte** [comment]
Aha! It looks as though adding type="number" made all the difference for me. Thanks for your work on this, and it now seems perfect!
