### ISSUE TITLE
feature requests: onEditing hook, wysiwyg hook, focusOnCreate

### ISSUE THREAD

**Issue by etaiklein** [JackAdams/meteor-editable-text#36]
Three requests:
1. I want to hook in further functionality, like conditional formatting, while editing.
2. I'd also like to hook into when wysiwyg is toggled.
3. I'd like to be able to focus on my field in edit mode after create

What's the best way to do these? If there isn't one I'd like to request it. Thanks!

**Comment by JackAdams** [comment]
1. Conditional formatting while editing should be possible by using a helper with: `{{> editableText ... inputStyle=styleBasedOnCondition ... }}` in the widget initialization where `styleBasedOnCondition` is a template helper.
2. I don't think there's any way to hook into this yet.
3. Check out the source for http://editable-text-demo.meteor.com/ -- this focuses on the field after creation (but it does use the widget to do the creating).  One alternative is to wrap the widget in an element with `class="editable-text-trigger"` and use code to trigger a click on that element.  You'd probably need to put a `data-id` attribute on the element as well (for targeting purposes) and might have to wrap the click-triggering code in a `Meteor.defer` block.

**Comment by etaiklein** [comment]
1. Ah, I wasn't clear. I want to toggle a show/hide a different element while editing an editable text field. The only way I can see how to do this is a "startEditing" hook
2. requested!
3. I looked at the editable-text-demo source and it doesn't appear to use data-id or meteor.defer. How editable-text-trigger works doesn't appear clear to me. Also, triggering a click on an editable-text or editable-text-trigger element doesn't appear to open editing for me. Is there a simple meteorpad example out there for this?

**Comment by JackAdams** [comment]
I think I should get an award for "Least helpful reply ever on an issue".  Give me a few hours and I'll try to do better.

**Comment by etaiklein** [comment]
Haha, no worries. You DO get an award for fastest replies ever. Your project and responsiveness has been incredibly helpful.

**Comment by JackAdams** [comment]
Ran out of time tonight and simply have to go to bed.  I can see a way to add those hooks in though and will try again tomorrow night.

**Comment by JackAdams** [comment]
0.7.26 has `onStartEditing` and `onStopEditing` callbacks.  Hope they help. I'll try to get to the other two issues in the next few days.

**Comment by etaiklein** [comment]
awesome. thank you!

**Comment by JackAdams** [comment]
Regarding (3):

Lines 21-27 in `/main.html` of [this meteorpad example](http://meteorpad.com/pad/RKq4xS7QWTyvfuNuW/Editable%20text%20test) shows how to use the widget to do inserts (adding players to the leaderboard app), making use of the `editable-text-trigger` class (remove it and try clicking the + on the button to see its effect).  Note: I also had to change line 44.  Doing it this way, the newly inserted document field is automatically put into edit mode.

I've also added some code (look for `.manual-insert`) to show how the editable text can be triggered after document creation using regular document creation followed by triggering a click on an element with the class `editable-text-trigger`. Lines 29-31 in `/main.html` and lines 17-20 in `/client/app.js`.

Will work on (2) soon.

**Comment by JackAdams** [comment]
I went to implement (2) and then realized that I'm not quite sure what "when wysiwyg is toggled" means.  Do you mean:
1) when you reveal the toolbar by pressing the little caret button, or 
2) when you click on some text and it gets surrounded by the editor frame (toolbar still hidden)?
For 2) the `onStartEditing` and `onStopEditing` callbacks would work
For 1) there will be `onHideToolbar` and `onShowToolbar` callbacks in the next release, which is just a few days away
