### ISSUE TITLE
wysiwyg: underline doesn't save / cannot toggle superscript or subscript

### ISSUE THREAD

**Issue by etaiklein** [JackAdams/meteor-editable-text#37]
on http://editable-text-demo.meteor.com/

underlining text doesn't stay underlined after saving.

after making text a superscript or subscript there is no way to return it to a regular size.

Thanks!

**Comment by JackAdams** [comment]
You're quite right.  The underlining was me forgetting to whitelist `<u>` tags and the superscript/subscript thing is a browser problem (works on Firefox, not on Chrome).  The underlining will be fixed in the next release, but the superscript/subscript problem will take a bit longer.

**Comment by JackAdams** [comment]
0.7.26 should fix the underlining problem

**Comment by JackAdams** [comment]
0.8.0 will fix the subscript/superscript problem (will be released in a day or two)
