### ISSUE TITLE
Can't update user profile data

### ISSUE THREAD

**Issue by ghost** [JackAdams/meteor-editable-text#42]
This code doesn't update the profile.city field:
{{> editableText collection="Meteor.users" field="profile.city" userCanEdit=userEditProfile}}

I have not made any changes to allow/deny rules for user profiles.  Any idea how to solve this?

**Comment by JackAdams** [comment]
Try:

```
{{> editableText collection="users" field="profile.city" userCanEdit=userEditProfile}}
```

I'm pretty sure the collection name has to be the name of the collection in Mongo, not Meteor.

**Comment by ghost** [comment]
Thank you!  It worked.

At first I was using 'users' for collection:
`{{> editableText collection="users" field="city" userCanEdit=userEditProfile}}`
But my data context was originally {{currentUser.profile}} rather than {{currentUser}} which also failed to update.

I actually changed 'users' to 'Meteor.users' based on this stack exchange answer:
http://stackoverflow.com/a/29136690/5195277
