### ISSUE TITLE
Can't get edited text field to update database

### ISSUE THREAD

**Issue by lqlau** [JackAdams/meteor-editable-text#45]
I forked Leaderboard example from MeteorPad:

http://meteorpad.com/pad/7WTXgLi5awBdGT7gu/Copy%20of%20Leaderboard

I've made the Score column editable using meteor-editable-text.  

When I go and edit a player's score, it does not update the database.  The old Score value is still shown for the player.

What have I done wrong?

**Comment by JackAdams** [comment]
Replace `collection="Players"` with `collection="players"` (mongo db name not Mongo.Collection instance name).  This will be made clear in the docs in the next release.

**Comment by lqlau** [comment]
Awesomeness!  Works now.  Thank you for your help.
