### ISSUE TITLE
Date Fields, Editable Text and Local Timezones

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#47]
What is the recommended way of handling date strings as editable text?

I have several fields in my schema that are defined as Dates. The format of the date fields is, for example,
2015 Sep 15
If I use standard inserts and updates through methods, I am getting the results I am looking for - actual dates are (with local timezone portion) passed to the server.

But I assume that if I use editable-text features that what is being sent is actually a string with no timezone indicator, which gets interpreted at the server as using the server's timezone instead. Is this what is happening?

How can I ensure that Date strings changed through editable text are interpreted with the local timezone on both submission and display?

**Comment by JackAdams** [comment]
There is a way, using afterUpdate callbacks, where you convert the string (passed to the server via editableText methods) into a date object.  It would go something like this:

**BOTH**

```
EditableText.registerCallbacks({
  stringToDate: function(doc, Collection) {
    var newValueForDateField = new Date(doc.dateField); // doc.dateField will be a string
    Collection.update({_id: doc._id}, {$set: {dateField: newValueForDateField}});
  }
});
```

**CLIENT**

```
{{> editableText collection="myCollection" field="dateField" afterUpdate="stringToDate"}}
```

So it's write the wrong type to the db and then immediately overwrite it with the correct type.  Not ideal -- a hack, really.  This package only has low level support for strings and integers out of the box.
