### ISSUE TITLE
afterUpdate hook missing status object in widget data 

### ISSUE THREAD

**Issue by SatishGandham** [JackAdams/meteor-editable-text#48]
First of thanks for this widget. It made my work very simple, and made it very easy to implement features that I wouldn't have added other wise.

Before commit e06d0b5037efecfe6b5f87b346cbd240cae3b3d7
There used to be a status object which included the error details in the ''this'' in afterUpdate hook, using which I used to display the error.

```
EditableText.registerCallbacks({
  validateProfileUpdate: function (doc) {
    console.log(this)
    var errors = {}
    if (this.status.error) {
      errors[this.field] = this.status.error.message
      Session.set('userProfileUpdateErrors', errors)
      // $('span.et-YzJr8BEAKfm2kvwhQ').click()
      var selector = '.'+this.class
      //var inputSelector = '.'+this.inputClass
      var newValue = this.newValue
      setTimeout(function () {
        $(selector).click()
        $(selector).val(newValue)
      }, 0);
    } else {
      errors[this.field] = null
      Session.set('userProfileUpdateErrors', errors)
    }

  }
});
```

Since the change on September 8th, there is no status object. Is it a bug?
If not what is the alternate?

1
<img width="448" alt="screen shot 2015-09-15 at 1 52 38 pm" src="https://cloud.githubusercontent.com/assets/441914/9872271/cae1bcf8-5bb5-11e5-930a-8fc46498099e.png">

**Comment by JackAdams** [comment]
Hmmm....  I certainly didn't _mean_ to remove that.  I'll look into getting it back into the widget.  Thanks for reporting this (and tracking down the offending commit!).

**Comment by JackAdams** [comment]
Okay, that should be fixed in `0.8.3` (just released).  Let me know if it isn't.

**Comment by SatishGandham** [comment]
It's fixed. Thank you :+1:

**Comment by SatishGandham** [comment]
Looks like you also forget to update the version number a lot :)

**Comment by JackAdams** [comment]
Which version number?  Git version, you mean?  Yeah, that'd be right.  I don't think I've ever done it.  I just update the package version number in `package.js` and `meteor publish`. :-p
