### ISSUE TITLE
What happened to this.oldValue? (Revisited from #49)

### ISSUE THREAD

**Issue by mvanio** [JackAdams/meteor-editable-text#50]
As #49 : this.oldValue is always undefined regardless of using `beforeUpdate` or `afterUpdate`.

```
EditableText.registerCallbacks({
  beNumeric: function(){
    console.log(this.oldValue);
    console.log(this.newValue);
  }
});
```

results in:

```
I20150922-16:53:47.511(1)? undefined
I20150922-16:53:47.511(1)? 12
```

Here's how I'm triggering the callback:

```
<td>
  {{> editableText inputStyle="inStyle" beforeUpdate="beNumeric" type="number" collection="funnyfolks" field="jokes.read.aloud.times"}}
</td>
```

I'm using 0.8.4 and I know you said this was fixed but it seems not to be. Am I missing something?

**Comment by JackAdams** [comment]
No, you're absolutely right.  It's still not fixed properly.  Will release 0.8.5 later today.  And if that doesn't fix it, I'll deprecate this package on the grounds of maintainer incompetence!  (Not really.)

Thank you for persisting with this.

**Comment by JackAdams** [comment]
I'm pretty sure I've got it this time.  I did have `this.oldValue` was working, but only for top level fields.  Now it's working for nested fields, which I notice is what you have there.  `0.8.5` is tested and working for nested fields.

**Comment by mvanio** [comment]
Thank you kindly. I didn't think to mention it was a nested field, sorry
about that.
I'll try 0.8.5 this evening.

**Comment by JackAdams** [comment]
No. That's all right. It was a genuine bug and I'm glad you persisted with it. I'm grateful.

**Comment by mvanio** [comment]
0.8.5 is working fine, thanks for the fix!
However, I now appear to need to use a Meteor 1.2rc due to the error:

```
Errors while adding packages:
While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: babrahams:editable-text 0.8.5
```

(and so far this has not affected any other packages in a serious way).
