### ISSUE TITLE
value= with beforeUpdate=

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#55]
A field from my doc needs to be converted to a new format before being displayed, then converted back to its original format after it is updated.

I am trying to use the following
{{> editableText collection="deals" field="signDate"  value=signDateInNewFormat editingValue=signDateInNewFormat acceptEmpty=true beforeUpdate="storeInOrigFormat"}}

When I use the above in my template the doc field is converted to my new format while being displayed and edited, but the beforeUpdate hook does not seem to work correctly. The function I specify is called, but newValue is always null. If I use this.newValue in its place, then the converted newValue, when returned, is ignored anyway.

Using the parameter editingValue, or leaving it out also seems to make no difference, and I'm not even sure if it is required.

**Comment by JackAdams** [comment]
The `beforeUpdate` function needs to return the modified value, not an object. e.g.

```
EditableText.registerCallbacks({
  beforeUpdateCallback: function () {
    return new Date(this.newValue);
  }
});
```

I'll look into the `editingValue` issue.

**Comment by dpatte** [comment]
I am returning a string. signDate is a string.

**Comment by JackAdams** [comment]
So the function registered as `storeInOrigFormat` is returning a string and it's still not working, right?

**Comment by dpatte** [comment]
or must i update this.newValue and return that?

**Comment by dpatte** [comment]
yes. signDate is a string. I return a string, and it is not working.

**Comment by dpatte** [comment]
```
EditableText.registerCallbacks({
  storeInOrigFormat: function() {
    if (this.newValue=="") return; // blank is OK

    // check if entered date was a valid date in display format
    var dt = new Date(this.newValue);
    var disp = YYYYMMMDD(dt); // 2015 Sep 1
    if (disp==this.newValue)
    {
      var fd = YYYY_MM_DD(dt); // convert to db format '2015-09-01'
      return fd; // yes, return in db format
    }
    else
      return this.value; // no, return original fixed date string
  }
});
```

(I have modified the above make the function name consistent with the one in my tag)

**Comment by JackAdams** [comment]
This is the right syntax. I'll do some tests to see what's going on.

**Comment by dpatte** [comment]
Just a note: I am using your v0.8.4. I am actually stuck on a recent version of Meteor 1.1 due to blocking issues with other modules that are preventing me from upgrading to Meteor 1.2. I'm not sure if this might be relevant to the problem I am having here. Thanks.

**Comment by dpatte** [comment]
another question. does the beforeUpdate callback have to be accessible on the server?

**Comment by JackAdams** [comment]
Yes, that's the reason. There was a bug in older versions of the editable text package. As a stopgap, you could clone the latest version of the package into your /packages directory and change the versionsFrom in the package.js file to suit your needs.

**Comment by JackAdams** [comment]
Yes. The `beforeUpdate` callback needs to be accessible on the server if it's going to be used to modify the value.

**Comment by dpatte** [comment]
I have made the callback accessible to the server, and it is working much better. I still have an issue when I reject the new input - and will get back to you on that.

**Comment by dpatte** [comment]
This is now working - sort of.
I git cloned the package and left the package.js file as is.

But now, editable-text-trigger is no longer working

**Comment by dpatte** [comment]
Yes, this solves the original problem for me, but the editable-text-trigger is no longer working for me at all.

**Comment by dpatte** [comment]
All fine now ofter i back-included gwendall:body-events

**Comment by JackAdams** [comment]
Thanks for letting me know about that editable-text-trigger issue.  I thought MDG had sorted out the body.events thing, so I removed the dependency on gwendall:body-events.  I'll put gwendall:body-events back as a dependency in the next release.

**Comment by dpatte** [comment]
Is the editable-text-trigger issue now resolved in the latest version?

**Comment by JackAdams** [comment]
Yes, should be.

**Comment by dpatte** [comment]
I changed back to your latest version, from the patched package I was using, and it works. Thanks.

**Comment by JackAdams** [comment]
Great. Thanks for confirming that.
