### ISSUE TITLE
Not firing: onStopEditing = function(item){}

### ISSUE THREAD

**Issue by AlbinoGeek** [JackAdams/meteor-editable-text#59]
With the signature as follows:

``` coffee
options = 
  acceptEmpty: false
  removeEmpty: false
  substitute: ' <i class="orange configure icon"></i>'
  saveOnFocusout: false
  onStopEditing: (item) ->
    console.log this
    console.log item
    return true
```

Two bugs:
- The field is still saved if (enter) is pressed, but not if Focusout.
- My onStopEditing is never called, neither console.log hits.

**Comment by AlbinoGeek** [comment]
Compiled JS:

``` js
var options = {
  'acceptEmpty': false,
  'removeEmpty': false,
  'substitute': ' <i class="orange configure icon"></i>',
  'saveOnFocusout': false,
  'onStopEditing': function(item) {
    console.log(this);
    console.log(item);
    return true;
  }
};
```

**Comment by JackAdams** [comment]
Ah yes ... the `onStopEditing` should be a string reference to a function registered using `EditableText.registerCallbacks`.  You can' t put a function directly in there.  Have a read through of the README.md.

The `saveOnFocusout` is `true` by default, but you can suppress this by setting it to false, as you've done.  It has no effect on pressing enter to save -- that will always save the changed value.

**Comment by AlbinoGeek** [comment]
@JackAdams How are you meant to manually validate the input then?  Wouldn't the "enter always saves" make the `saveOnFocusout` not as useful?  (Especially if you're already taking advantage of the `esc` cancels editing, etc.)

The idea is one could validate the input, and return `true` if the value should be saved, else `false` if the value should not be saved.  This would intentionally be client side validation for the purpose of warning or guiding the user towards correct input (using `mizao:autocomplete` for example...)

Alternatively, since `onStopEditing` already hands in the document both pre-modification and post-modification, one could either return a mutation (see: dburles:collection-handlers), or simply the modified collection (as passed), to be inserted (in case your validation made changes, such as adding to the document, etc.)

---

At the moment, I need to register a callback for the `beforeInsert` , and then mangle the document if I want to stop your plugin from saving the document, which is not a clean work-around.
