### ISSUE TITLE
editable text 'TypeError

### ISSUE THREAD

**Issue by joseterrera** [JackAdams/meteor-editable-text#60]
I'l trying to add the text but getting this issue on the console:
Exception in template helper: TypeError: Cannot use 'in' operator to search for 'body' in null
https://github.com/joseterrera/meteorBlog/blob/master/client/templates/posts/post_submit.html
am I missing a step?

**Comment by JackAdams** [comment]
It sounds like the context is not set as a document from the specified collection (where the widget appears in your template).

**Comment by JackAdams** [comment]
Sorry. Just noticed you'd given a github link - I'll take a look when I get a moment.

**Comment by joseterrera** [comment]
thanks! it may look simple but I'm pretty stuck with it.

**Comment by JackAdams** [comment]
You're missing:

```
Template.postSubmit.helpers({
  postSubmit: function () {
    return Posts.findOne(); // Put some real query in the findOne
  }
});
```

If the post doesn't exist yet, you need:

```
Template.postSubmit.helpers({
  postSubmit: function () {
    return {body: ''};
  }
});
```

and, in the template:

```
{{> editableText context=postSubmit collection="posts" field="body" wysiwyg=true autoInsert=true}}
```

**Comment by joseterrera** [comment]
I've tried adding those helpers into my postSubmit but it didn't help.

**Comment by JackAdams** [comment]
Take a look at these lines of the demo app:
https://github.com/JackAdams/editable-text-demo/blob/master/editable-text-demo.html#L17
https://github.com/JackAdams/editable-text-demo/blob/master/editable-text-demo.js#L109-L136 (in particular 116-118)
