### ISSUE TITLE
Does not work correctly with modals

### ISSUE THREAD

**Issue by echo66** [JackAdams/meteor-editable-text#65]
Greetings!

I'm trying to use this package with Bootstrap 3 Modals or Jquery UI packages. Unfortunately, when I use a template inside a modal, after editing a field using that modal, the HTML content goes back to the old value. This problem only exists within the modal because the values for the editable-text containers outside the modal are updated correctly.

I should note that if I change the field value with an editable-text container from outside the modal, the containers inside the modal will stay with the old value.

I even tried to do a similar thing but without the modal:
``javascript

var doc = AnnotationsBoards.findOne({_id: "qHWqsxsdqdZnMADpN"});
var div = document.createElement("div");
document.body.appendChild(div);
var view = Blaze.renderWithData(Template['annotations_board_info'], doc, div);

``

This will produce the same issue as the modal, after I edit the field value.

**Comment by echo66** [comment]
TIL:

http://docs.meteor.com/#/full/blaze_renderwithdata

_data Object or Function
The data context to use, or a function returning a data context. If a function is provided, it will be reactively re-run._

If I use a function

var view = Blaze.renderWithData(Template['annotations_board_info'], function() { return AnnotationsBoards.findOne({_id: "qHWqsxsdqdZnMADpN"}); }, div);

everything will be just fine. :smile: 

So, the problem was that I didn't know about this "small" difference.

**Comment by JackAdams** [comment]
Ah yes, I seem to remember having a similar issue when I was working with modals a couple of years back. Thanks for posting the solution for others who may come across a similar thing.
