### ISSUE TITLE
How to create editable callback for array fields?

### ISSUE THREAD

**Issue by chrisco23** [JackAdams/meteor-editable-text#66]
Before I switched from iron router to flow router, I was able to use editable-text on an array inside of rendered, as in this callback snippet.  Now with flow router, I can't figure out how to do the same thing.  Can anyone advise?

```
Template._userPortfolios.rendered = function() {
  var tmplInst;
  tmplInst = this;
  return this.autorun(function() {
    Blaze.getData();
    tmplInst.$(".shares.editable").editable("destroy").editable({
      display: function(value) {},
      success: function(response, sharesString) {
        shares = parseInt(sharesString);
        that = this;
        _.each(tmplInst.data.tickers, function(ticker, key, updatedTickers) {
          if (ticker.symbol == that.id) {
            updatedTickers[key].shares = shares;
          }
        });
        UserPortfolios.update({
          _id: tmplInst.data._id,
        },
        {
          $set: {
            tickers : tmplInst.data.tickers
          }
        });
        calcRecommendations(tmplInst.data);
        calcRebalance(tmplInst.data);
      }
    });
```

**Comment by chrisco23** [comment]
This is my template html work-in-progress for the above:

```
          {{ #each tickers }}
          <tr>
            <td style="white-space: nowrap">{{ symbol }}</td>
            <td class="hide-on-small-only">{{ name }}</td>
            <td>{{ percent }}%</td>
            <td>{{ actualPercent }}%</td>
            <td>
              <div id="{{ symbol }}" class="shares editable" data-type="text">
                  <!-- below comment is what works for a regular field
                        but shares is a field in the array 'tickers' (at same
                        level as cash) -->
<!--                {{> editableText editingValue=cash value=cashH field="cash"
                collection="userPortfolios"}}-->
                {{ shares }}
              </div>
            </td>
            <td>{{ recommendation recommendedShares shares }}</td>
            <td class="currency hide-on-small-only">{{ quote symbol }}</td>
            <td class="currency">{{ subtotal symbol }}</td>
          </tr>
          {{ /each }}
```

**Comment by JackAdams** [comment]
The part in the `rendered` callback looks like it's using a different editable text package.  Are they in conflict, both trying to control the DOM?

The discussion on [this issue](https://github.com/JackAdams/meteor-editable-text/issues/46) might help.

**Comment by chrisco23** [comment]
Thanks.  I think you're right.  At some point I had tried another editable package.  Forgot about that because I had some commented out code from quite some time ago that I was looking at.

Also, the other issue to which you refer sounds to be exactly like my situation, but it seems meteorpad.com (your solution example?) no longer exists or else is down.

I don't suppose you still have an example of finding this index from a helper?

**Comment by JackAdams** [comment]
Yes, it's a pity the meteorpad.com has been shut down -- just saw that now.

There may be some example code in one of the other closed issues.

The `babrahams:editable-list` package is made for manipulating arrays of string values, if that helps. (I can't remember if it handles number values as well.)

**Comment by chrisco23** [comment]
I'm just now returning to this project and this problem again.  I wonder if you have any suggestion on how I could make an editable for the situation as shown (document image from robomongo, and output table from template)?  I just want to be able to edit shares within the table (ideally).

![userportfolio_pic](https://cloud.githubusercontent.com/assets/241907/14339437/63e715ce-fc33-11e5-8336-109fafda4ba8.jpg)
![userportfolio_table_pic](https://cloud.githubusercontent.com/assets/241907/14339440/6979c16c-fc33-11e5-9034-e3c0779e98c7.jpg)

**Comment by JackAdams** [comment]
You need to give the `field` parameter a path into the document to reach the `shares` field. For example, in your case: 

```
field="tickers.0.shares"
```

The trouble is getting that `0` value.
Instead of:

```
{{#each tickers}}
  <tr > ... </tr>
{{/each}}
```

You'll need:

```
{{#each indexedTickers}}
  <tr >
  ...
    <td>
      {{> editableText collection="users" context=.. field=field type="number"}}
    </td> 
  ...
  </tr>
{{/each}}
```

where `indexedTickers` is supplied by a helper:

```
Template.ticker_table.helpers({
  indexedTickers: function () {
    return _.map(this.tickers, function (ticker, index) {
      return _.extend(ticker, {index, index});
    });
  },
  // Context for the following is inside the each, so a single ticker object
  field: function () {
    return 'tickers.' + this.index + '.shares';
  }
});
```

I hope all that makes sense.  I think it would work.

**Comment by chrisco23** [comment]
Ah, this is brilliant!  Absolutely makes my day.

I learned a couple things here.  It hadn't occurred to me I could use a helper for the #each (guess I've never hit that need before) and I completely didn't know one could do "context=.."

**Comment by JackAdams** [comment]
Cool.  Glad it worked out.  Now this will be my "go to" code sample for this situation (in the absence of the meteorpad one).
