### ISSUE TITLE
stop eating the enter

### ISSUE THREAD

**Issue by txs** [JackAdams/meteor-editable-text#67]
I love this package! However the textarea cannot accept "enter" it trigger as a focus out.
Is there a way I can still use the textarea and have the enter function? and autosave?

**Comment by JackAdams** [comment]
Try SHIFT + Enter or COMMAND + Enter.  I think one of those does a carriage return.

**Comment by txs** [comment]
is there a way I can change it to enter?

**Comment by JackAdams** [comment]
I don't think there's an option for that at the moment.  I'll accept a PR.

EDIT: Just did a quick test.  SHIFT + ENTER will let you do a carriage return in the textarea, but it doesn't display the `\n` as a `<br />`.  This needs fixing somehow.  Thanks for bringing it up.

**Comment by JackAdams** [comment]
Now you can write `noSaveOnReturn=true` when initializing the widget.
