### ISSUE TITLE
wysiwyg not working

### ISSUE THREAD

**Issue by txs** [JackAdams/meteor-editable-text#68]
I cannot use the trigger . since it gives a recursive bug.
I want to try the wysiwyg. and when I clicked I can get to the UI.
However, I cannot edit the code. what's wrong. should I use {{ or {{{?
the page just don't work!

**Comment by JackAdams** [comment]
Take a read of this: https://github.com/JackAdams/meteor-editable-text#triggering-widget

The other thing people have had trouble with recursion is when wrapping the widget with an `a` tag.

**Comment by txs** [comment]
I still having the issue if I wrap it in the trigger tag. After the recursion thw wysiwyg is still not triggering
I cannot edit the text

**Comment by JackAdams** [comment]
Take a look at [the source of the demo](https://github.com/JackAdams/editable-text-demo/blob/master/editable-text-demo.html#L27-L29) -- that has a wysiwyg surrounded by an `editable-text-trigger`.

**Comment by txs** [comment]
whenever I use the trigger the whole app just stop for 5 secs

**Comment by JackAdams** [comment]
Weird.  Can you post a code example?  I might be able to spot what's going on.

**Comment by txs** [comment]
`<div` class="~trigger">
{{> editableTextArea context=singleCareDoc collection="cares" field=fieldWhy
          wysiwyg=true
                    substitute='<div class="" style=" color: rgba(128, 128, 128, 0.72); height: 0px; top: 5px; position: relative;"></div>' }}
`</div>`

**Comment by txs** [comment]
May you fix the enter one first
That one is in a hurry please

**Comment by JackAdams** [comment]
I'm not likely to get to either of them anytime soon. The best thing to do if you need something fixed in a hurry is to put together a PR.

**Comment by txs** [comment]
I will publish a new package thanks

2016-03-25 15:53 GMT+08:00 Brent Abrahams notifications@github.com:
