### ISSUE TITLE
switch to edit mode for all editable's on a page

### ISSUE THREAD

**Issue by krawalli** [JackAdams/meteor-editable-text#7]
What about have a possibility (by e.g. buttonclick) to set a webpage in "edit" mode, so that all editable-text fields turn into inputs.

With that, you could easily navigate by _tab_ key between the fields.
After that you can press a "save button" (like it is for textarea) to bulk-save those fields.

**Comment by JackAdams** [comment]
Yes. That sounds do-able.  I was also thinking of having and option available where you don't need to click to edit at all -- i.e. it always displays an input field and you just edit the text then click 'Enter' to persist it (like the pad name in Meteorpad).  Might need to build in a little yellow fade in that case to indicate the save has occurred.

**Comment by krawalli** [comment]
Yeah, sounds good.

I like the possibility of "editable", but sometimes e.g. add new documents, I need a "real" form. Now I'm trying to avoid to build extra template for this.

**Comment by JackAdams** [comment]
I see what you mean.  I'll have a think about how this might be done.

**Comment by JackAdams** [comment]
[This package](http://formation.meteor.com/fields) looks like a pretty good match for the functionality you're after.

**Comment by krawalli** [comment]
Nice find!

Thank you.
