### ISSUE TITLE
Is a collection required?

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#74]
I like your module, and appreciate what you have done to enhance it for me in the past.

Now, I think I may need another enhancement, or at least perhaps a workaround....

I'd like to be able to use your module for inline editing of
- standard js variables
- reactiveVars
- sessionVariables

In effect, I would like the ability to edit any of the above, but using the features you currently have for editing fields in collections.

Possible?

**Comment by JackAdams** [comment]
Sorry about the late reply.  Yes, at the moment this only works for fields in documents from collections.

**Comment by JackAdams** [comment]
Oops, just saw your comment in #71.
