### ISSUE TITLE
Do Method calls work from a beforeUpdate callback?

### ISSUE THREAD

**Issue by t3db0t** [JackAdams/meteor-editable-text#75]
I need to update a particular field in two different collections (yeah), so I'm trying to do this:

```
EditableText.registerCallbacks({
  updateName: function(doc, Collection, newValue, modifier){
    if(Meteor.isClient){
        Meteor.call("updateParticipantName", Router.current().params.id, doc._id, newValue);
    }
    // we don't actually want to change anything
    return newValue;
  }
});
```

But the method call doesn't get called at all.  I can successfully call the method from the client console. I've tried everything I can think of—what am I missing?  Or is there a better way to update multiple collections 'at once'?

**Comment by JackAdams** [comment]
Is the `updateName` function being called in the widget?
It should look like this:

```
{{> editableText collection="yourCollection" field="fieldName" beforeUpdate="updateName"}}
```

**Comment by JackAdams** [comment]
I've put a little (tested and working) example together:

```
{{> editableText collection="yourCollection" field="fieldName" beforeUpdate="callMethod"}}
```

```
EditableText.registerCallbacks({
  callMethod : function (doc, Collection, newValue) {
    Meteor.call("testMethod", doc);
    return newValue;
  }
});

Meteor.methods({
  "testMethod" : function (doc) {
    console.log("Method doc: ", doc);  
  }
});
```

**Comment by t3db0t** [comment]
Yes, the callback is definitely being called, and everything in it runs except for method calls?! I've got to be missing something simple but I've tried everything I can think of. I haven't tried a minimal repro yet though :(

**Comment by JackAdams** [comment]
Hang on, I think those callbacks are only run server side, not client side. That would explain it.  Let me check the codebase and do some tests.  I'll get back to you soon.

**Comment by t3db0t** [comment]
They are running ONLY client side in my tests...

**Comment by JackAdams** [comment]
Yep.  What's happening is that the callback you're seeing run on the client is actually the result of a method stub being run on the client (the method that the editable text package runs server side for actual db updates and also has a client side stub run for optimistic UI).  The real callback function is being run on the server.  Method calls (i.e. your method call) from method stubs (i.e. from the editableText package's db write method) aren't actually fired off to the server for processing.

**Comment by JackAdams** [comment]
You'd need to remove the `Meteor.isClient` block and get the `Router.current().params.id` info to the callback that is run on the server by some other cunning method.  Let me have a think ... I'll get back to you soon.

**Comment by JackAdams** [comment]
Okay, I've just released a new version (0.8.20) with a `data` attribute to the widget that allows you to pass arbitrary data from client to server.  First `meteor update`, then your code would then look like this:

TEMPLATE (CLIENT)

```
{{> editableText collection="yourCollection" field="fieldName" beforeUpdate="callMethod" data=requiredId}}
```

TEMPLATE HELPER FILE (CLIENT)

```
Template.myTemplate.helpers({
  requiredId: function () {
    return Router.current().params.id;
  }
});
```

COMMON

```
EditableText.registerCallbacks({
  updateName: function(doc, Collection, newValue, modifier){
    Meteor.call("updateParticipantName", this.data, doc._id, newValue);
    // we don't actually want to change anything
    return newValue;
  }
});

Meteor.methods({
  "updateParticipantName" : function (requiredId, docId, newValue) { 
     console.log(requiredId, docId, newValue);
     // ... method code ...
  }
});
```

**Comment by t3db0t** [comment]
Wow, amazing! Thank you so much!

**Comment by t3db0t** [comment]
Great, this works—thanks again :D
