### ISSUE TITLE
Problem trying to enter zero '0'

### ISSUE THREAD

**Issue by gduquesnay** [JackAdams/meteor-editable-text#78]
The following code
```
 +editableText(collection="teams" field="sessionTimeoutMs" acceptEmpty=true type="number" placeholder="enter session timeout in MS.  0 to disable" substitute='<i class="fa fa-pencil"></
```
cause '0' to disappear when entered and shows the substitute pencil icon instead.

**Comment by JackAdams** [comment]
Thanks for bringing this up. I'll look into it over the next week or two.

**Comment by JackAdams** [comment]
Thanks again for alerting me to this.  It's a genuine bug and will be fixed in a new release of the package in a few hours' time.

**Comment by JackAdams** [comment]
0.8.31 should fix this.
