### ISSUE TITLE
Security: Do a check() on all arguments

### ISSUE THREAD

**Issue by workflow** [JackAdams/meteor-editable-text#8]
https://atmospherejs.com/meteor/audit-argument-checks reports a missing check at least here:

```
I20150201-13:44:52.311(1)? Exception while invoking method '_editableTextWrite' Error: Did not    check() all arguments during call to '_editableTextWrite'
```

Thx for this great package!

**Comment by JackAdams** [comment]
Nice catch. Thanks. The fix will be out in the next release, which should be published in an hour or two.
