### ISSUE TITLE
acceptEmpty = function ?

### ISSUE THREAD

**Issue by dpatte** [JackAdams/meteor-editable-text#83]
I have a case of three inline fields. For each field I want to accept empty if either of the other fields is not empty. possible?

**Comment by JackAdams** [comment]
Yes. Instead of 
```
acceptEmpty=true
```
write
```
acceptEmpty=otherFieldsNotEmpty
```
and create a helper:
```
otherFieldsNotEmpty : function () {
  var otherFieldsNotEmpty = // logic for testing other fields not being empty goes here
  return otherFieldsNotEmpty;
}
```
That approach should work as long as the `otherFieldsNotEmpty` helper is reactive.

**Comment by dpatte** [comment]
Great! Glad the feature is provided
