### ISSUE TITLE
Negative numbers are stored as positives

### ISSUE THREAD

**Issue by micktaiwan** [JackAdams/meteor-editable-text#85]
When using type="number" any negative number is stored as positive

**Comment by JackAdams** [comment]
Yes, you're right. I'll publish a fix sometime today.

**Comment by JackAdams** [comment]
Version `0.9.11` (just published) will allow negative numbers if you pass `allowNegative=true` to the widget.

**Comment by micktaiwan** [comment]
Thank you very much ! That was quick !
