### ISSUE TITLE
data for callback

### ISSUE THREAD

**Issue by krawalli** [JackAdams/meteor-editable-text#9]
Do I miss something or is there currently no way for a executed registered callback on update to know what changed?

Something like oldvalue / newvalue.

**Comment by JackAdams** [comment]
Probably not.  I almost never use callbacks, so I haven't paid much attention to their implementation.  I'm currently working on applying the principles from your first PR to all insert, update, remove calls in the _editableTextWrite method (regardless of whether collection2 is present), so data.status.error and data.status.result will be available.  Would that help with what you're after?

**Comment by krawalli** [comment]
no, i dont think so, since that is "only" the success or failure text from simple schema.

callbacks should now:
- collection this belongs to
- the field the data is for
- the old value
- the new value

Where does the 'modifier' come from? Maybe there is only a little to extend there.

**Comment by JackAdams** [comment]
Ah... I see what you mean.  All of that info is available in callbacks via `this`.

**Comment by krawalli** [comment]
Sorry, but only 3 of those 4 are available.

the _new_value_ is missing

**Comment by JackAdams** [comment]
You mean the modifier when doing an update?  I'll make it available somehow.  Maybe via `this.modifier`.

**Comment by krawalli** [comment]
just the new value would be better

**Comment by JackAdams** [comment]
Yep.  Just came to that conclusion myself.  `this.newValue` will be available in callbacks in the next release.  Due to go live in about 10-15 minutes.

**Comment by JackAdams** [comment]
For convenience and consistency, I'm going to throw in `this.oldValue` as well.

Thanks for keeping me honest with your attention to detail, by the way. :-)

**Comment by krawalli** [comment]
nice, thanks!

**Comment by JackAdams** [comment]
New version of the package just went live on atmosphere.
